# compose2nix --project home-server --runtime docker -env_files .env
networks:
  arr:
    name: arr
  exposed:
    name: exposed
  thelounge:
    name: thelounge
  # HACK: Create a custom network for the wireguard server because for some reason other network subnets
  # become unreachable if the container is just assigned to the existing networks where containers already exist.
  # Use "0" as a prefix to have it get chosen as the one to get an IP from by docker.
  wireguard:
    name: 0wireguard
  dozzle:
    name: dozzle
  socket-proxy-dozzle:
    name: socket-proxy-dozzle
  komga:
    name: komga
  authentik:
    name: authentik
    external: true
  ldap:
    name: ldap
    external: true

services:
  dnsmasq:
    image: 4km3/dnsmasq:2.90-r3
    container_name: dnsmasq
    volumes:
      - ${PATH_CONFIG_BASE}/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf:ro
    ports:
      - 5300:53/tcp
      - 5300:53/udp
      - 54000:51820/udp
      - 54001:51821/tcp
    cap_add:
      - NET_ADMIN
    networks:
      - wireguard

  # https://github.com/wg-easy/wg-easy
  # sudo docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw 'password'
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=<Host IP>
      # sudo docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw 'password'
      - PASSWORD_HASH=<Hash>
      - PORT=51821
      - WG_PORT=51820
    # env_file:
    #   - ${config.sops.secrets.wg-easy-env.path}
    volumes:
      - ${PATH_CONFIG_BASE}/wg-easy:/etc/wireguard
    # Handled in dnsmasq
    # ports:
    #   - 54000:51820/udp
    #   - 54001:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    network_mode: service:dnsmasq
    depends_on:
      - dnsmasq

  # https://github.com/wollomatic/socket-proxy
  # More generic permissions: https://github.com/linuxserver/docker-socket-proxy
  dockerproxy-dozzle:
    container_name: dockerproxy-dozzle
    image: wollomatic/socket-proxy:1
    command:
      - '-loglevel=info'
      - '-allowfrom=dozzle' # allow only the container "dozzle"
      - '-listenip=0.0.0.0'
      - '-allowGET=/v1\.[0-9]{1,2}/(_ping|info|events|containers/(json|([a-f0-9]{12}|[a-f0-9]{64})/(json|stats|logs)))'
      - '-allowHEAD=/_ping'
      - '-watchdoginterval=300'
      - '-stoponwatchdog'
      - '-shutdowngracetime=10'
    restart: unless-stopped
    read_only: true
    mem_limit: 64M
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    user: nobody:docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy-dozzle

  # https://dozzle.dev/guide/getting-started
  # PODMAN: https://github.com/amir20/dozzle?tab=readme-ov-file#installation-on-podman
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v8
    user: nobody:nogroup
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
    depends_on:
      - dockerproxy-dozzle
    environment:
      DOZZLE_REMOTE_HOST: tcp://dockerproxy-dozzle:2375
    ports:
      # QBit is already using 8080
      - 8090:8080
    networks:
      - socket-proxy-dozzle
      - dozzle

  cloudflared-tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared
    # restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<token>
    # env_file:
    #   - ${config.sops.secrets.cloudflared-env.path}
    networks:
      - exposed

  # https://docs.linuxserver.io/general/swag/#swag
  # https://github.com/linuxserver/reverse-proxy-confs?tab=readme-ov-file#how-to-use-these-reverse-proxy-configs
  # https://www.linuxserver.io/blog/zero-trust-hosting-and-reverse-proxy-via-cloudflare-swag-and-authelia
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      # - URL=
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - CERTPROVIDER=
      - DNSPLUGIN=cloudflare
      # - EMAIL=
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=
      - STAGING=false
      - SWAG_AUTORELOAD=true
      # https://github.com/linuxserver/docker-mods/tree/swag-cloudflare-real-ip
      # Real IP works with a separate container, no need for the cloudflared mod
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip
    # env_file:
    #   - ${config.sops.secrets.swag-env.path}
    volumes:
      - ${PATH_CONFIG_BASE}/swag:/config
      # https://jellyfin.org/docs/general/networking/fail2ban/
      - ${PATH_CONFIG_BASE}/jellyfin/log:/jellyfin:ro
      # https://docs.overseerr.dev/extending-overseerr/fail2ban
      # This blog provides a pre-made hybrid filter for fail2ban that works with both overseerr and jellyseerr
      # Pretty easy to arrive at it, but it's convenient
      # https://zzuo123.github.io/blog/securing-server/
      - ${PATH_CONFIG_BASE}/jellyseerr/logs:/jellyseerr:ro
    ports:
      - 443:443
      - 80:80 #optional
    # restart: unless-stopped
    networks:
      - exposed

  swag-internal:
    image: lscr.io/linuxserver/swag
    container_name: swag-internal
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      # - URL=
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - CERTPROVIDER=
      - DNSPLUGIN=cloudflare
      # - EMAIL=
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=
      - STAGING=false
      - SWAG_AUTORELOAD=true
      - DOCKER_MODS=
    # env_file:
    #   - ${config.sops.secrets.swag-env.path}
    volumes:
      - ${PATH_CONFIG_BASE}/swag-internal:/config
    ports:
      - 4433:443
      - 800:80 #optional
    # restart: unless-stopped
    networks:
      - wireguard
      - arr
      - exposed
      - thelounge
      - authentik
      - ldap
      - dozzle
      - komga

  # https://hotio.dev/containers/jellyfin/
  # Migration: Compare paths in
  # https://jellyfin.org/docs/general/administration/migrate/#migrating-linux-install-to-docker
  # https://hotio.dev/containers/jellyfin/#configuration
  # https://github.com/NixOS/nixpkgs/blob/40916ded4ad5fe4bcc18963217c3a026db505c7f/nixos/modules/services/misc/jellyfin.nix#L27-L63
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - '8096:8096'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/jellyfin:/config
      - ${PATH_MEDIASERVER_DATA_BASE}/media:/data/media:ro
    # https://jellyfin.org/docs/general/installation/container#with-hardware-acceleration
    devices: # Needed for hardware acceleration/transcoding
      - /dev/dri:/dev/dri
      - nvidia.com/gpu=all
    networks:
      - arr
      - ldap
      - exposed

  # https://docs.jellyseerr.dev/
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    ports:
      - 5055:5055
    volumes:
      - ${PATH_CONFIG_BASE}/jellyseerr:/app/config
    # restart: unless-stopped
    networks:
      - arr
      - exposed

  # https://github.com/gotson/komga
  # https://komga.org/docs/category/installation
  komga:
    # https://komga.org/docs/installation/docker#version-tags
    image: gotson/komga:1.x
    container_name: komga
    volumes:
      - ${PATH_CONFIG_BASE}/komga:/config
      - ${PATH_MEDIASERVER_DATA_BASE}/media:/data
    ports:
      - 25600:25600
    user: '1000:1000'
    environment:
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      # https://komga.org/docs/installation/docker#increase-memory-limit
      # - JAVA_TOOL_OPTIONS=-Xmx4g
    # restart: unless-stopped
    networks:
      - arr
      - komga
      - exposed

  # https://github.com/Snd-R/komf
  # https://github.com/Snd-R/komf-userscript
  komf:
    image: sndxr/komf:latest
    container_name: komf
    ports:
      - '8085:8085'
    user: '1000:1000'
    environment:
      - KOMF_LOG_LEVEL=INFO
      # optional jvm options. Example config for low memory usage. Runs guaranteed cleanup up every 3600000ms(1hour)
      # - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
    volumes:
      # https://github.com/Snd-R/komf?tab=readme-ov-file#example-applicationyml-config
      # Use /api/v1/libraries in komga for library IDs
      # - ${config.sops.secrets.komf.path}
      - ${PATH_CONFIG_BASE}/komf:/config #path to directory with application.yml and database file
    restart: unless-stopped
    networks:
      - komga

  # https://hotio.dev/containers/qbittorrent/#starting-the-container
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release-4.6.7
    dns:
      - 1.1.1.1
      - 9.9.9.9
    ports:
      - '8080:8080'
      - '8118:8118'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
      # VPN Config
      # https://hotio.dev/containers/qbittorrent/#wireguard
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      # https://protonvpn.com/vpn-servers
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN=8080/tcp # Expose WebUI
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1 # Disable IPv6
    # devices:
    #   - /dev/net/tun:/dev/net/tun # OPTIONAL, READ THIS(9)
    volumes:
      - ${PATH_CONFIG_BASE}/qbittorrent:/config
      - /CHANGEME:/config/wireguard/wg0.conf
      - ${PATH_MEDIASERVER_DATA_BASE}/torrents:/data/torrents
    networks:
      - arr

  # https://github.com/StuffAnThings/qbit_manage/wiki
  qbit_manage:
    container_name: qbit_manage
    image: ghcr.io/stuffanthings/qbit_manage:latest
    volumes:
      - ${PATH_CONFIG_BASE}/qbit_manage/:/config:rw
      - /CHANGEME:/config/config.yml
      - ${PATH_MEDIASERVER_DATA_BASE}/torrents/:/data/torrents:rw
      - ${PATH_CONFIG_BASE}/qbittorrent:/qbittorrent/:ro
    environment:
      - QBT_RUN=false
      - QBT_SCHEDULE=1440
      - QBT_CONFIG=config.yml
      - QBT_LOGFILE=activity.log
      - QBT_CROSS_SEED=false
      - QBT_RECHECK=false
      - QBT_CAT_UPDATE=false
      - QBT_TAG_UPDATE=false
      - QBT_REM_UNREGISTERED=false
      - QBT_REM_ORPHANED=false
      - QBT_TAG_TRACKER_ERROR=false
      - QBT_TAG_NOHARDLINKS=false
      - QBT_SHARE_LIMITS=false
      - QBT_SKIP_CLEANUP=false
      - QBT_DRY_RUN=false
      - QBT_LOG_LEVEL=INFO
      - QBT_DIVIDER==
      - QBT_WIDTH=100
    # restart: on-failure:2
    networks:
      - arr
    depends_on:
      - qbittorrent

  # https://www.cross-seed.org/docs
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    user: 1000:1000
    ports:
      - '2468:2468'
    volumes:
      - ${PATH_CONFIG_BASE}/cross-seed:/config
      - /CHANGEME:/config/config.js
      - ${PATH_CONFIG_BASE}/qbittorrent/data/BT_backup:/torrents:ro # Keep read-only
      - ${PATH_MEDIASERVER_DATA_BASE}/torrents:/data/torrents
    command: daemon
    # restart: unless-stopped
    networks:
      - arr

  # https://hotio.dev/containers/sonarr/#starting-the-container
  sonarr-tv-hd:
    container_name: sonarr-tv-hd
    image: ghcr.io/hotio/sonarr
    ports:
      - '8989:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/sonarr-tv-hd:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://github.com/Suwayomi/Suwayomi-Server
  # https://github.com/suwayomi/Suwayomi-Server-docker
  suwayomi:
    # For some reason "preview" == "latest"
    image: ghcr.io/suwayomi/suwayomi-server:preview
    container_name: suwayomi
    environment:
      - DEBUG=false
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      # The save path is hardcoded
      # https://github.com/Suwayomi/Suwayomi-Server-docker?tab=readme-ov-file#downloads-folder
      - ${PATH_MEDIASERVER_DATA_BASE}/media/comics/suwayomi/downloads:/home/suwayomi/.local/share/Tachidesk/downloads
      - ${PATH_CONFIG_BASE}/suwayomi:/home/suwayomi/.local/share/Tachidesk
    ports:
      - '4567:4567'
    user: nobody:nogroup
    # restart: on-failure:3
    networks:
      - arr

  sonarr-tv-uhd:
    container_name: sonarr-tv-uhd
    image: ghcr.io/hotio/sonarr
    ports:
      - '8990:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/sonarr-tv-uhd:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  sonarr-anime:
    container_name: sonarr-anime
    image: ghcr.io/hotio/sonarr
    ports:
      - '8991:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/sonarr-anime:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://hotio.dev/containers/radarr/#starting-the-container
  radarr-movies-hd:
    container_name: radarr-movies-hd
    image: ghcr.io/hotio/radarr
    ports:
      - '7878:7878'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/radarr-movies-hd:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://hotio.dev/containers/radarr/#starting-the-container
  radarr-movies-uhd:
    container_name: radarr-movies-uhd
    image: ghcr.io/hotio/radarr
    ports:
      - '7879:7878'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/radarr-movies-uhd:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://readarr.com/
  readarr:
    container_name: readarr
    image: ghcr.io/hotio/readarr
    ports:
      - '8787:8787'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/readarr:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://hotio.dev/containers/prowlarr/#starting-the-container
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - '9696:9696'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/prowlarr:/config
    networks:
      - arr

  flaresolverr:
    container_name: flaresolverr
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    ports:
      - '8191:8191'
    # restart: unless-stopped
    networks:
      - arr

  # https://recyclarr.dev/wiki/installation/docker/
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    # Change this to use config.nix.users.*
    # This is ok as recyclarr is a rootless container
    user: nobody:nogroup
    volumes:
      - ${PATH_CONFIG_BASE}/recyclarr:/config
      - /CHANGEME:/config/recyclarr.yml
      - /CHANGEME2:/config/secrets.yml
    environment:
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      # This is a default
      # - CRON_SCHEDULE=@daily
    networks:
      - arr
    depends_on:
      - sonarr-anime
      - sonarr-tv-hd
      - radarr-movies-hd

  # https://thelounge.chat/docs
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - '9010:9000'
    # restart: always
    user: '1000:1000'
    volumes:
      - ${PATH_CONFIG_BASE}/thelounge:/var/opt/thelounge
    networks:
      - thelounge
